# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from secure_access.models.dlp_rule_event import DlpRuleEvent
from secure_access.models.list_ai_guardrails_dlp_rule_events import ListAiGuardrailsDlpRuleEvents
from secure_access.models.list_real_time_dlp_rule_events import ListRealTimeDlpRuleEvents
from secure_access.models.list_saa_s_api_dlp_rule_events import ListSaaSApiDlpRuleEvents

from secure_access.api_client import ApiClient, RequestSerialized
from secure_access.api_response import ApiResponse
from secure_access.rest import RESTResponseType


class DLPRuleEventsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_all_ai_guardrails_events(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time. ")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time. ")],
        action: Annotated[Optional[StrictStr], Field(description="The type of action applied to the content. ")] = None,
        severity: Annotated[Optional[StrictStr], Field(description="The severity of the DLP rule that triggered the event.")] = None,
        identity_type: Annotated[Optional[StrictStr], Field(description="The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. ")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of events to return on a page in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="A number that represents an index in the collection.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListAiGuardrailsDlpRuleEvents:
        """List AI Guardrails DLP Rule Events

        List the DLP events triggered by the AI Guardrails DLP rules applied to the AI Guardrails use cases. 

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time.  (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time.  (required)
        :type to: str
        :param action: The type of action applied to the content. 
        :type action: str
        :param severity: The severity of the DLP rule that triggered the event.
        :type severity: str
        :param identity_type: The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. 
        :type identity_type: str
        :param limit: The maximum number of events to return on a page in the response.
        :type limit: int
        :param offset: A number that represents an index in the collection.
        :type offset: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_ai_guardrails_events_serialize(
            var_from=var_from,
            to=to,
            action=action,
            severity=severity,
            identity_type=identity_type,
            limit=limit,
            offset=offset,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListAiGuardrailsDlpRuleEvents",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_all_ai_guardrails_events_with_http_info(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time. ")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time. ")],
        action: Annotated[Optional[StrictStr], Field(description="The type of action applied to the content. ")] = None,
        severity: Annotated[Optional[StrictStr], Field(description="The severity of the DLP rule that triggered the event.")] = None,
        identity_type: Annotated[Optional[StrictStr], Field(description="The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. ")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of events to return on a page in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="A number that represents an index in the collection.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListAiGuardrailsDlpRuleEvents]:
        """List AI Guardrails DLP Rule Events

        List the DLP events triggered by the AI Guardrails DLP rules applied to the AI Guardrails use cases. 

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time.  (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time.  (required)
        :type to: str
        :param action: The type of action applied to the content. 
        :type action: str
        :param severity: The severity of the DLP rule that triggered the event.
        :type severity: str
        :param identity_type: The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. 
        :type identity_type: str
        :param limit: The maximum number of events to return on a page in the response.
        :type limit: int
        :param offset: A number that represents an index in the collection.
        :type offset: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_ai_guardrails_events_serialize(
            var_from=var_from,
            to=to,
            action=action,
            severity=severity,
            identity_type=identity_type,
            limit=limit,
            offset=offset,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListAiGuardrailsDlpRuleEvents",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_all_ai_guardrails_events_without_preload_content(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time. ")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time. ")],
        action: Annotated[Optional[StrictStr], Field(description="The type of action applied to the content. ")] = None,
        severity: Annotated[Optional[StrictStr], Field(description="The severity of the DLP rule that triggered the event.")] = None,
        identity_type: Annotated[Optional[StrictStr], Field(description="The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. ")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of events to return on a page in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="A number that represents an index in the collection.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List AI Guardrails DLP Rule Events

        List the DLP events triggered by the AI Guardrails DLP rules applied to the AI Guardrails use cases. 

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time.  (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time.  (required)
        :type to: str
        :param action: The type of action applied to the content. 
        :type action: str
        :param severity: The severity of the DLP rule that triggered the event.
        :type severity: str
        :param identity_type: The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. 
        :type identity_type: str
        :param limit: The maximum number of events to return on a page in the response.
        :type limit: int
        :param offset: A number that represents an index in the collection.
        :type offset: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_ai_guardrails_events_serialize(
            var_from=var_from,
            to=to,
            action=action,
            severity=severity,
            identity_type=identity_type,
            limit=limit,
            offset=offset,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListAiGuardrailsDlpRuleEvents",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_all_ai_guardrails_events_serialize(
        self,
        var_from,
        to,
        action,
        severity,
        identity_type,
        limit,
        offset,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if action is not None:
            
            _query_params.append(('action', action))
            
        if severity is not None:
            
            _query_params.append(('severity', severity))
            
        if identity_type is not None:
            
            _query_params.append(('identityType', identity_type))
            
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/dlp/aiGuardrails/events',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_all_real_time_events(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time. ")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time. ")],
        action: Annotated[Optional[StrictStr], Field(description="The type of action applied to the content. ")] = None,
        severity: Annotated[Optional[StrictStr], Field(description="The severity of the DLP rule that triggered the event.")] = None,
        identity_type: Annotated[Optional[StrictStr], Field(description="The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. ")] = None,
        application_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application associated with the event.")] = None,
        application_category_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application category associated with the event. ")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of events to return on a page in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="A number that represents an index in the collection.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListRealTimeDlpRuleEvents:
        """List Real-Time DLP Rule Events

        List the DLP events triggered by the Real-time DLP rules applied to the private or internet resources. 

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time.  (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time.  (required)
        :type to: str
        :param action: The type of action applied to the content. 
        :type action: str
        :param severity: The severity of the DLP rule that triggered the event.
        :type severity: str
        :param identity_type: The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. 
        :type identity_type: str
        :param application_id: The unique identifier of the application associated with the event.
        :type application_id: int
        :param application_category_id: The unique identifier of the application category associated with the event. 
        :type application_category_id: int
        :param limit: The maximum number of events to return on a page in the response.
        :type limit: int
        :param offset: A number that represents an index in the collection.
        :type offset: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_real_time_events_serialize(
            var_from=var_from,
            to=to,
            action=action,
            severity=severity,
            identity_type=identity_type,
            application_id=application_id,
            application_category_id=application_category_id,
            limit=limit,
            offset=offset,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListRealTimeDlpRuleEvents",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_all_real_time_events_with_http_info(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time. ")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time. ")],
        action: Annotated[Optional[StrictStr], Field(description="The type of action applied to the content. ")] = None,
        severity: Annotated[Optional[StrictStr], Field(description="The severity of the DLP rule that triggered the event.")] = None,
        identity_type: Annotated[Optional[StrictStr], Field(description="The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. ")] = None,
        application_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application associated with the event.")] = None,
        application_category_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application category associated with the event. ")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of events to return on a page in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="A number that represents an index in the collection.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListRealTimeDlpRuleEvents]:
        """List Real-Time DLP Rule Events

        List the DLP events triggered by the Real-time DLP rules applied to the private or internet resources. 

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time.  (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time.  (required)
        :type to: str
        :param action: The type of action applied to the content. 
        :type action: str
        :param severity: The severity of the DLP rule that triggered the event.
        :type severity: str
        :param identity_type: The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. 
        :type identity_type: str
        :param application_id: The unique identifier of the application associated with the event.
        :type application_id: int
        :param application_category_id: The unique identifier of the application category associated with the event. 
        :type application_category_id: int
        :param limit: The maximum number of events to return on a page in the response.
        :type limit: int
        :param offset: A number that represents an index in the collection.
        :type offset: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_real_time_events_serialize(
            var_from=var_from,
            to=to,
            action=action,
            severity=severity,
            identity_type=identity_type,
            application_id=application_id,
            application_category_id=application_category_id,
            limit=limit,
            offset=offset,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListRealTimeDlpRuleEvents",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_all_real_time_events_without_preload_content(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time. ")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time. ")],
        action: Annotated[Optional[StrictStr], Field(description="The type of action applied to the content. ")] = None,
        severity: Annotated[Optional[StrictStr], Field(description="The severity of the DLP rule that triggered the event.")] = None,
        identity_type: Annotated[Optional[StrictStr], Field(description="The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. ")] = None,
        application_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application associated with the event.")] = None,
        application_category_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application category associated with the event. ")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of events to return on a page in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="A number that represents an index in the collection.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Real-Time DLP Rule Events

        List the DLP events triggered by the Real-time DLP rules applied to the private or internet resources. 

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time.  (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time.  (required)
        :type to: str
        :param action: The type of action applied to the content. 
        :type action: str
        :param severity: The severity of the DLP rule that triggered the event.
        :type severity: str
        :param identity_type: The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. 
        :type identity_type: str
        :param application_id: The unique identifier of the application associated with the event.
        :type application_id: int
        :param application_category_id: The unique identifier of the application category associated with the event. 
        :type application_category_id: int
        :param limit: The maximum number of events to return on a page in the response.
        :type limit: int
        :param offset: A number that represents an index in the collection.
        :type offset: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_real_time_events_serialize(
            var_from=var_from,
            to=to,
            action=action,
            severity=severity,
            identity_type=identity_type,
            application_id=application_id,
            application_category_id=application_category_id,
            limit=limit,
            offset=offset,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListRealTimeDlpRuleEvents",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_all_real_time_events_serialize(
        self,
        var_from,
        to,
        action,
        severity,
        identity_type,
        application_id,
        application_category_id,
        limit,
        offset,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if action is not None:
            
            _query_params.append(('action', action))
            
        if severity is not None:
            
            _query_params.append(('severity', severity))
            
        if identity_type is not None:
            
            _query_params.append(('identityType', identity_type))
            
        if application_id is not None:
            
            _query_params.append(('applicationId', application_id))
            
        if application_category_id is not None:
            
            _query_params.append(('applicationCategoryId', application_category_id))
            
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/dlp/realTime/events',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_all_saa_sapi_events(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time. ")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time. ")],
        action: Annotated[Optional[StrictStr], Field(description="The type of action applied to the content. ")] = None,
        severity: Annotated[Optional[StrictStr], Field(description="The severity of the DLP rule that triggered the event.")] = None,
        identity_type: Annotated[Optional[StrictStr], Field(description="The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. ")] = None,
        application_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application associated with the event.")] = None,
        application_category_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application category associated with the event. ")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of events to return on a page in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="A number that represents an index in the collection.")] = None,
        exposure: Annotated[Optional[StrictStr], Field(description="The exposure level assigned to the scanned content.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListSaaSApiDlpRuleEvents:
        """List SaaS API DLP Rule Events

        List the DLP events triggered by the SaaS API DLP rules applied to the SaaS applications. 

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time.  (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time.  (required)
        :type to: str
        :param action: The type of action applied to the content. 
        :type action: str
        :param severity: The severity of the DLP rule that triggered the event.
        :type severity: str
        :param identity_type: The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. 
        :type identity_type: str
        :param application_id: The unique identifier of the application associated with the event.
        :type application_id: int
        :param application_category_id: The unique identifier of the application category associated with the event. 
        :type application_category_id: int
        :param limit: The maximum number of events to return on a page in the response.
        :type limit: int
        :param offset: A number that represents an index in the collection.
        :type offset: int
        :param exposure: The exposure level assigned to the scanned content.
        :type exposure: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_saa_sapi_events_serialize(
            var_from=var_from,
            to=to,
            action=action,
            severity=severity,
            identity_type=identity_type,
            application_id=application_id,
            application_category_id=application_category_id,
            limit=limit,
            offset=offset,
            exposure=exposure,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListSaaSApiDlpRuleEvents",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_all_saa_sapi_events_with_http_info(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time. ")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time. ")],
        action: Annotated[Optional[StrictStr], Field(description="The type of action applied to the content. ")] = None,
        severity: Annotated[Optional[StrictStr], Field(description="The severity of the DLP rule that triggered the event.")] = None,
        identity_type: Annotated[Optional[StrictStr], Field(description="The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. ")] = None,
        application_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application associated with the event.")] = None,
        application_category_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application category associated with the event. ")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of events to return on a page in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="A number that represents an index in the collection.")] = None,
        exposure: Annotated[Optional[StrictStr], Field(description="The exposure level assigned to the scanned content.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListSaaSApiDlpRuleEvents]:
        """List SaaS API DLP Rule Events

        List the DLP events triggered by the SaaS API DLP rules applied to the SaaS applications. 

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time.  (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time.  (required)
        :type to: str
        :param action: The type of action applied to the content. 
        :type action: str
        :param severity: The severity of the DLP rule that triggered the event.
        :type severity: str
        :param identity_type: The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. 
        :type identity_type: str
        :param application_id: The unique identifier of the application associated with the event.
        :type application_id: int
        :param application_category_id: The unique identifier of the application category associated with the event. 
        :type application_category_id: int
        :param limit: The maximum number of events to return on a page in the response.
        :type limit: int
        :param offset: A number that represents an index in the collection.
        :type offset: int
        :param exposure: The exposure level assigned to the scanned content.
        :type exposure: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_saa_sapi_events_serialize(
            var_from=var_from,
            to=to,
            action=action,
            severity=severity,
            identity_type=identity_type,
            application_id=application_id,
            application_category_id=application_category_id,
            limit=limit,
            offset=offset,
            exposure=exposure,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListSaaSApiDlpRuleEvents",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_all_saa_sapi_events_without_preload_content(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time. ")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time. ")],
        action: Annotated[Optional[StrictStr], Field(description="The type of action applied to the content. ")] = None,
        severity: Annotated[Optional[StrictStr], Field(description="The severity of the DLP rule that triggered the event.")] = None,
        identity_type: Annotated[Optional[StrictStr], Field(description="The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. ")] = None,
        application_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application associated with the event.")] = None,
        application_category_id: Annotated[Optional[StrictInt], Field(description="The unique identifier of the application category associated with the event. ")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of events to return on a page in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="A number that represents an index in the collection.")] = None,
        exposure: Annotated[Optional[StrictStr], Field(description="The exposure level assigned to the scanned content.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List SaaS API DLP Rule Events

        List the DLP events triggered by the SaaS API DLP rules applied to the SaaS applications. 

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filters for data that appears **after** this time.  (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filters for data that appears **before** this time.  (required)
        :type to: str
        :param action: The type of action applied to the content. 
        :type action: str
        :param severity: The severity of the DLP rule that triggered the event.
        :type severity: str
        :param identity_type: The type of the identity associated with the event, for example: `directory_user`, `directory_group`, or `network`. 
        :type identity_type: str
        :param application_id: The unique identifier of the application associated with the event.
        :type application_id: int
        :param application_category_id: The unique identifier of the application category associated with the event. 
        :type application_category_id: int
        :param limit: The maximum number of events to return on a page in the response.
        :type limit: int
        :param offset: A number that represents an index in the collection.
        :type offset: int
        :param exposure: The exposure level assigned to the scanned content.
        :type exposure: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_saa_sapi_events_serialize(
            var_from=var_from,
            to=to,
            action=action,
            severity=severity,
            identity_type=identity_type,
            application_id=application_id,
            application_category_id=application_category_id,
            limit=limit,
            offset=offset,
            exposure=exposure,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListSaaSApiDlpRuleEvents",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_all_saa_sapi_events_serialize(
        self,
        var_from,
        to,
        action,
        severity,
        identity_type,
        application_id,
        application_category_id,
        limit,
        offset,
        exposure,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if action is not None:
            
            _query_params.append(('action', action))
            
        if severity is not None:
            
            _query_params.append(('severity', severity))
            
        if identity_type is not None:
            
            _query_params.append(('identityType', identity_type))
            
        if application_id is not None:
            
            _query_params.append(('applicationId', application_id))
            
        if application_category_id is not None:
            
            _query_params.append(('applicationCategoryId', application_category_id))
            
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if exposure is not None:
            
            _query_params.append(('exposure', exposure))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/dlp/saasApi/events',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_dlp_event_details_by_id(
        self,
        event_type: Annotated[StrictStr, Field(description="The type of the event. Use one of the event types. * For Real-Time events, use `realTime`. * For SaaS API events, use `saasApi`. * For AI Guardrails events, use `aiGuardrails`. ")],
        id: Annotated[StrictStr, Field(description="The unique identifier of the event.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> DlpRuleEvent:
        """Get DLP Event Details

        Get the event details for a specific type of DLP rule using the event's unique ID. The event type is either Real Time, SaaS API, or AI Guardrails DLP rules. The response includes the event details, associated rule information, and classifications.

        :param event_type: The type of the event. Use one of the event types. * For Real-Time events, use `realTime`. * For SaaS API events, use `saasApi`. * For AI Guardrails events, use `aiGuardrails`.  (required)
        :type event_type: str
        :param id: The unique identifier of the event. (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_dlp_event_details_by_id_serialize(
            event_type=event_type,
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DlpRuleEvent",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_dlp_event_details_by_id_with_http_info(
        self,
        event_type: Annotated[StrictStr, Field(description="The type of the event. Use one of the event types. * For Real-Time events, use `realTime`. * For SaaS API events, use `saasApi`. * For AI Guardrails events, use `aiGuardrails`. ")],
        id: Annotated[StrictStr, Field(description="The unique identifier of the event.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[DlpRuleEvent]:
        """Get DLP Event Details

        Get the event details for a specific type of DLP rule using the event's unique ID. The event type is either Real Time, SaaS API, or AI Guardrails DLP rules. The response includes the event details, associated rule information, and classifications.

        :param event_type: The type of the event. Use one of the event types. * For Real-Time events, use `realTime`. * For SaaS API events, use `saasApi`. * For AI Guardrails events, use `aiGuardrails`.  (required)
        :type event_type: str
        :param id: The unique identifier of the event. (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_dlp_event_details_by_id_serialize(
            event_type=event_type,
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DlpRuleEvent",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_dlp_event_details_by_id_without_preload_content(
        self,
        event_type: Annotated[StrictStr, Field(description="The type of the event. Use one of the event types. * For Real-Time events, use `realTime`. * For SaaS API events, use `saasApi`. * For AI Guardrails events, use `aiGuardrails`. ")],
        id: Annotated[StrictStr, Field(description="The unique identifier of the event.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get DLP Event Details

        Get the event details for a specific type of DLP rule using the event's unique ID. The event type is either Real Time, SaaS API, or AI Guardrails DLP rules. The response includes the event details, associated rule information, and classifications.

        :param event_type: The type of the event. Use one of the event types. * For Real-Time events, use `realTime`. * For SaaS API events, use `saasApi`. * For AI Guardrails events, use `aiGuardrails`.  (required)
        :type event_type: str
        :param id: The unique identifier of the event. (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_dlp_event_details_by_id_serialize(
            event_type=event_type,
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DlpRuleEvent",
            '400': "ApiErrorResponse",
            '401': "ApiErrorResponse",
            '403': "ApiErrorResponse",
            '404': "ApiErrorResponse",
            '500': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_dlp_event_details_by_id_serialize(
        self,
        event_type,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if event_type is not None:
            _path_params['eventType'] = event_type
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/dlp/{eventType}/events/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


