# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Optional, Union
from typing_extensions import Annotated
from secure_access.models.get_tunnel_events200_response import GetTunnelEvents200Response

from secure_access.api_client import ApiClient, RequestSerialized
from secure_access.api_response import ApiResponse
from secure_access.rest import RESTResponseType


class NetworkTunnelsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_tunnel_events(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time.")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time.")],
        limit: Annotated[Union[StrictFloat, StrictInt], Field(description="The maximum number of records to return from the collection.")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A number that represents an index in the collection.")] = None,
        order: Annotated[Optional[StrictStr], Field(description="A string that describes how to order the results: ascending (`asc`) or descending (`desc`).")] = None,
        timezone: Annotated[Optional[StrictStr], Field(description="Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.")] = None,
        servicename: Annotated[Optional[StrictStr], Field(description="A comma-separated list of service type used to filter the collection.")] = None,
        network_tunnel_level: Annotated[Optional[StrictStr], Field(description="A comma-separated list of log levels used to filter the collection of network tunnel logs.")] = None,
        networktunnelgrouplabel: Annotated[Optional[StrictStr], Field(description="A comma-separated list of network tunnel group labels used to filter the collection.")] = None,
        datacenterip: Annotated[Optional[StrictStr], Field(description="A comma-separated list of data center IP addresses.")] = None,
        message: Annotated[Optional[StrictStr], Field(description="A comma-separated list of event messages.")] = None,
        region: Annotated[Optional[StrictStr], Field(description="A comma-separated list of AWS or Azure regions where the system deployed the network tunnel groups.")] = None,
        searchtext: Annotated[Optional[StrictStr], Field(description="A comma-separated list of text used to search the collection.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetTunnelEvents200Response:
        """Get Network Tunnel Logs

        List the events for the network tunnels deployed in the organization.  **Access Scope:** Reports > Granular Events > Read-Only

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time. (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time. (required)
        :type to: str
        :param limit: The maximum number of records to return from the collection. (required)
        :type limit: float
        :param offset: A number that represents an index in the collection.
        :type offset: float
        :param order: A string that describes how to order the results: ascending (`asc`) or descending (`desc`).
        :type order: str
        :param timezone: Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.
        :type timezone: str
        :param servicename: A comma-separated list of service type used to filter the collection.
        :type servicename: str
        :param network_tunnel_level: A comma-separated list of log levels used to filter the collection of network tunnel logs.
        :type network_tunnel_level: str
        :param networktunnelgrouplabel: A comma-separated list of network tunnel group labels used to filter the collection.
        :type networktunnelgrouplabel: str
        :param datacenterip: A comma-separated list of data center IP addresses.
        :type datacenterip: str
        :param message: A comma-separated list of event messages.
        :type message: str
        :param region: A comma-separated list of AWS or Azure regions where the system deployed the network tunnel groups.
        :type region: str
        :param searchtext: A comma-separated list of text used to search the collection.
        :type searchtext: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_tunnel_events_serialize(
            var_from=var_from,
            to=to,
            limit=limit,
            offset=offset,
            order=order,
            timezone=timezone,
            servicename=servicename,
            network_tunnel_level=network_tunnel_level,
            networktunnelgrouplabel=networktunnelgrouplabel,
            datacenterip=datacenterip,
            message=message,
            region=region,
            searchtext=searchtext,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetTunnelEvents200Response",
            '400': "Reporting400Error",
            '401': "Reporting401Error",
            '403': "Reporting403Error",
            '404': "Reporting404Error",
            '500': "Reporting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_tunnel_events_with_http_info(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time.")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time.")],
        limit: Annotated[Union[StrictFloat, StrictInt], Field(description="The maximum number of records to return from the collection.")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A number that represents an index in the collection.")] = None,
        order: Annotated[Optional[StrictStr], Field(description="A string that describes how to order the results: ascending (`asc`) or descending (`desc`).")] = None,
        timezone: Annotated[Optional[StrictStr], Field(description="Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.")] = None,
        servicename: Annotated[Optional[StrictStr], Field(description="A comma-separated list of service type used to filter the collection.")] = None,
        network_tunnel_level: Annotated[Optional[StrictStr], Field(description="A comma-separated list of log levels used to filter the collection of network tunnel logs.")] = None,
        networktunnelgrouplabel: Annotated[Optional[StrictStr], Field(description="A comma-separated list of network tunnel group labels used to filter the collection.")] = None,
        datacenterip: Annotated[Optional[StrictStr], Field(description="A comma-separated list of data center IP addresses.")] = None,
        message: Annotated[Optional[StrictStr], Field(description="A comma-separated list of event messages.")] = None,
        region: Annotated[Optional[StrictStr], Field(description="A comma-separated list of AWS or Azure regions where the system deployed the network tunnel groups.")] = None,
        searchtext: Annotated[Optional[StrictStr], Field(description="A comma-separated list of text used to search the collection.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetTunnelEvents200Response]:
        """Get Network Tunnel Logs

        List the events for the network tunnels deployed in the organization.  **Access Scope:** Reports > Granular Events > Read-Only

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time. (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time. (required)
        :type to: str
        :param limit: The maximum number of records to return from the collection. (required)
        :type limit: float
        :param offset: A number that represents an index in the collection.
        :type offset: float
        :param order: A string that describes how to order the results: ascending (`asc`) or descending (`desc`).
        :type order: str
        :param timezone: Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.
        :type timezone: str
        :param servicename: A comma-separated list of service type used to filter the collection.
        :type servicename: str
        :param network_tunnel_level: A comma-separated list of log levels used to filter the collection of network tunnel logs.
        :type network_tunnel_level: str
        :param networktunnelgrouplabel: A comma-separated list of network tunnel group labels used to filter the collection.
        :type networktunnelgrouplabel: str
        :param datacenterip: A comma-separated list of data center IP addresses.
        :type datacenterip: str
        :param message: A comma-separated list of event messages.
        :type message: str
        :param region: A comma-separated list of AWS or Azure regions where the system deployed the network tunnel groups.
        :type region: str
        :param searchtext: A comma-separated list of text used to search the collection.
        :type searchtext: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_tunnel_events_serialize(
            var_from=var_from,
            to=to,
            limit=limit,
            offset=offset,
            order=order,
            timezone=timezone,
            servicename=servicename,
            network_tunnel_level=network_tunnel_level,
            networktunnelgrouplabel=networktunnelgrouplabel,
            datacenterip=datacenterip,
            message=message,
            region=region,
            searchtext=searchtext,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetTunnelEvents200Response",
            '400': "Reporting400Error",
            '401': "Reporting401Error",
            '403': "Reporting403Error",
            '404': "Reporting404Error",
            '500': "Reporting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_tunnel_events_without_preload_content(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time.")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time.")],
        limit: Annotated[Union[StrictFloat, StrictInt], Field(description="The maximum number of records to return from the collection.")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A number that represents an index in the collection.")] = None,
        order: Annotated[Optional[StrictStr], Field(description="A string that describes how to order the results: ascending (`asc`) or descending (`desc`).")] = None,
        timezone: Annotated[Optional[StrictStr], Field(description="Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.")] = None,
        servicename: Annotated[Optional[StrictStr], Field(description="A comma-separated list of service type used to filter the collection.")] = None,
        network_tunnel_level: Annotated[Optional[StrictStr], Field(description="A comma-separated list of log levels used to filter the collection of network tunnel logs.")] = None,
        networktunnelgrouplabel: Annotated[Optional[StrictStr], Field(description="A comma-separated list of network tunnel group labels used to filter the collection.")] = None,
        datacenterip: Annotated[Optional[StrictStr], Field(description="A comma-separated list of data center IP addresses.")] = None,
        message: Annotated[Optional[StrictStr], Field(description="A comma-separated list of event messages.")] = None,
        region: Annotated[Optional[StrictStr], Field(description="A comma-separated list of AWS or Azure regions where the system deployed the network tunnel groups.")] = None,
        searchtext: Annotated[Optional[StrictStr], Field(description="A comma-separated list of text used to search the collection.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Network Tunnel Logs

        List the events for the network tunnels deployed in the organization.  **Access Scope:** Reports > Granular Events > Read-Only

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time. (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time. (required)
        :type to: str
        :param limit: The maximum number of records to return from the collection. (required)
        :type limit: float
        :param offset: A number that represents an index in the collection.
        :type offset: float
        :param order: A string that describes how to order the results: ascending (`asc`) or descending (`desc`).
        :type order: str
        :param timezone: Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.
        :type timezone: str
        :param servicename: A comma-separated list of service type used to filter the collection.
        :type servicename: str
        :param network_tunnel_level: A comma-separated list of log levels used to filter the collection of network tunnel logs.
        :type network_tunnel_level: str
        :param networktunnelgrouplabel: A comma-separated list of network tunnel group labels used to filter the collection.
        :type networktunnelgrouplabel: str
        :param datacenterip: A comma-separated list of data center IP addresses.
        :type datacenterip: str
        :param message: A comma-separated list of event messages.
        :type message: str
        :param region: A comma-separated list of AWS or Azure regions where the system deployed the network tunnel groups.
        :type region: str
        :param searchtext: A comma-separated list of text used to search the collection.
        :type searchtext: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_tunnel_events_serialize(
            var_from=var_from,
            to=to,
            limit=limit,
            offset=offset,
            order=order,
            timezone=timezone,
            servicename=servicename,
            network_tunnel_level=network_tunnel_level,
            networktunnelgrouplabel=networktunnelgrouplabel,
            datacenterip=datacenterip,
            message=message,
            region=region,
            searchtext=searchtext,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetTunnelEvents200Response",
            '400': "Reporting400Error",
            '401': "Reporting401Error",
            '403': "Reporting403Error",
            '404': "Reporting404Error",
            '500': "Reporting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_tunnel_events_serialize(
        self,
        var_from,
        to,
        limit,
        offset,
        order,
        timezone,
        servicename,
        network_tunnel_level,
        networktunnelgrouplabel,
        datacenterip,
        message,
        region,
        searchtext,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if order is not None:
            
            _query_params.append(('order', order))
            
        if timezone is not None:
            
            _query_params.append(('timezone', timezone))
            
        if servicename is not None:
            
            _query_params.append(('servicename', servicename))
            
        if network_tunnel_level is not None:
            
            _query_params.append(('networkTunnelLevel', network_tunnel_level))
            
        if networktunnelgrouplabel is not None:
            
            _query_params.append(('networktunnelgrouplabel', networktunnelgrouplabel))
            
        if datacenterip is not None:
            
            _query_params.append(('datacenterip', datacenterip))
            
        if message is not None:
            
            _query_params.append(('message', message))
            
        if region is not None:
            
            _query_params.append(('region', region))
            
        if searchtext is not None:
            
            _query_params.append(('searchtext', searchtext))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/networkTunnelLogs',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


