# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from secure_access.models.access_rule_context import AccessRuleContext
from secure_access.models.behavior_analytics_context import BehaviorAnalyticsContext
from secure_access.models.severity_alert import SeverityAlert
from secure_access.models.status_alert import StatusAlert
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Alert(BaseModel):
    """
    The properties of the alert.
    """ # noqa: E501
    access_rule_context: Optional[AccessRuleContext] = None
    alert_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the alert.", alias="alertId")
    behavior_analytics_context: Optional[BehaviorAnalyticsContext] = None
    created_at: Optional[datetime] = Field(default=None, description="The time and date (ISO 8601 timestamp) when the system created the alert.")
    description: Optional[StrictStr] = Field(default=None, description="The description of the alert.")
    modified_at: Optional[datetime] = Field(default=None, description="The time and date (ISO 8601 timestamp) when the system last modified the alert.")
    name: Optional[StrictStr] = Field(default=None, description="The name of the alert.")
    organization_id: Optional[StrictInt] = Field(default=None, description="The unique identifier of the organization.")
    rule_id: Optional[StrictInt] = Field(default=None, description="The unique identifier of the associated rule.")
    rule_type_id: Optional[StrictInt] = Field(default=None, description="The identifier of the rule type.  **Connectivity** * 1: Network tunnel group disconnected * 2: No traffic through network tunnel group  **API Anomalies** * 3: Too many requests to get an access token * 4: High percentage of API errors * 5: Large number of rate limit errors * 6: More than one client using an API credential * 7: Authentication failures * 8: Programmatic creation of more than one API credential  **Data Usage** * 9: Data usage approaching limit  **Access Rule Changes** * 10: Rule creation, deletion, changing or reordering  **Behavior Analytics** * 11: Impossible travel detected * 12: Bulk upload operations * 13: Bulk download operations * 14: Bulk delete operations * 15: DLP violation spike * 16: Upload from high-risk countries * 17: Upload to high-risk countries")
    severity: Optional[SeverityAlert] = None
    status: Optional[StatusAlert] = None
    __properties: ClassVar[List[str]] = ["access_rule_context", "alertId", "behavior_analytics_context", "created_at", "description", "modified_at", "name", "organization_id", "rule_id", "rule_type_id", "severity", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Alert from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of access_rule_context
        if self.access_rule_context:
            _dict['access_rule_context'] = self.access_rule_context.to_dict()
        # override the default output from pydantic by calling `to_dict()` of behavior_analytics_context
        if self.behavior_analytics_context:
            _dict['behavior_analytics_context'] = self.behavior_analytics_context.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Alert from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access_rule_context": AccessRuleContext.from_dict(obj["access_rule_context"]) if obj.get("access_rule_context") is not None else None,
            "alertId": obj.get("alertId"),
            "behavior_analytics_context": BehaviorAnalyticsContext.from_dict(obj["behavior_analytics_context"]) if obj.get("behavior_analytics_context") is not None else None,
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "modified_at": obj.get("modified_at"),
            "name": obj.get("name"),
            "organization_id": obj.get("organization_id"),
            "rule_id": obj.get("rule_id"),
            "rule_type_id": obj.get("rule_type_id"),
            "severity": obj.get("severity"),
            "status": obj.get("status")
        })
        return _obj


