# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AllDestinationsScope(str, Enum):
    """
    The scope of all of the destinations for the DLP rule.
    """

    """
    allowed enum values
    """
    NONE = 'NONE'
    FILES_AND_FORMS = 'FILES_AND_FORMS'
    FILES_AND_VETTED_APPS_FORMS = 'FILES_AND_VETTED_APPS_FORMS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AllDestinationsScope from a JSON string"""
        return cls(json.loads(json_str))


