# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from secure_access.models.create_integration_jamf_config_container import CreateIntegrationJamfConfigContainer
from secure_access.models.jamf_config_input import JamfConfigInput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateIntegrationJamfInputBody(BaseModel):
    """
    CreateIntegrationJamfInputBody
    """ # noqa: E501
    config: Optional[CreateIntegrationJamfConfigContainer] = None
    jamf_config: Optional[JamfConfigInput] = Field(default=None, alias="jamfConfig")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=250)] = Field(description="The name of the integration.")
    tags: Optional[List[StrictStr]] = Field(default=None, description="The list of tags associated with the integration.")
    type: StrictStr = Field(description="Type of integration to create")
    __properties: ClassVar[List[str]] = ["config", "jamfConfig", "name", "tags", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['jamf.v1']):
            raise ValueError("must be one of enum values ('jamf.v1')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateIntegrationJamfInputBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of jamf_config
        if self.jamf_config:
            _dict['jamfConfig'] = self.jamf_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateIntegrationJamfInputBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "config": CreateIntegrationJamfConfigContainer.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "jamfConfig": JamfConfigInput.from_dict(obj["jamfConfig"]) if obj.get("jamfConfig") is not None else None,
            "name": obj.get("name"),
            "tags": obj.get("tags"),
            "type": obj.get("type")
        })
        return _obj


