# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from secure_access.models.classifier_evaluation_strategy import ClassifierEvaluationStrategy
from secure_access.models.data_classification_type import DataClassificationType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DataClassification(BaseModel):
    """
    Details of a data classification.
    """ # noqa: E501
    classifier_evaluation_strategy: Optional[ClassifierEvaluationStrategy] = Field(default=None, alias="classifierEvaluationStrategy")
    creation_time: Optional[StrictInt] = Field(default=None, description="The date and time represented in seconds since the UNIX Epoch when the system created the data classification.", alias="creationTime")
    data_identifiers: Optional[List[UUID]] = Field(default=None, description="The list of IDs for the data classifiers associated with the classification.", alias="dataIdentifiers")
    description: Optional[StrictStr] = Field(default=None, description="The detailed description of the classification.")
    excluded_data_identifiers: Optional[List[UUID]] = Field(default=None, description="The list of IDs for excluded classifiers associated with the classification.", alias="excludedDataIdentifiers")
    id: UUID = Field(description="The unique identifier of the classification.")
    modification_time: Optional[StrictInt] = Field(default=None, description="The date and time represented in seconds since the UNIX Epoch when the system updated the data classification.", alias="modificationTime")
    name: Annotated[str, Field(min_length=6, strict=True, max_length=255)] = Field(description="The name of the classification.")
    type: DataClassificationType
    __properties: ClassVar[List[str]] = ["classifierEvaluationStrategy", "creationTime", "dataIdentifiers", "description", "excludedDataIdentifiers", "id", "modificationTime", "name", "type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataClassification from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataClassification from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "classifierEvaluationStrategy": obj.get("classifierEvaluationStrategy"),
            "creationTime": obj.get("creationTime"),
            "dataIdentifiers": obj.get("dataIdentifiers"),
            "description": obj.get("description"),
            "excludedDataIdentifiers": obj.get("excludedDataIdentifiers"),
            "id": obj.get("id"),
            "modificationTime": obj.get("modificationTime"),
            "name": obj.get("name"),
            "type": obj.get("type")
        })
        return _obj


