# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DataClassificationType(str, Enum):
    """
    The type of the classification.
    """

    """
    allowed enum values
    """
    BUILT_MINUS_IN = 'built-in'
    BUILT_MINUS_IN_MINUS_AI_MINUS_DEFENSE = 'built-in-ai-defense'
    CUSTOM = 'custom'
    CUSTOM_MINUS_AI_MINUS_DEFENSE = 'custom-ai-defense'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataClassificationType from a JSON string"""
        return cls(json.loads(json_str))


