# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DeviceType(str, Enum):
    """
    The type of device that establishes the network tunnel. The default value is `other`.
    """

    """
    allowed enum values
    """
    ASA = 'ASA'
    AWS_S2S_VPN = 'AWS S2S VPN'
    AZURE_S2S_VPN = 'AZURE S2S VPN'
    FTD = 'FTD'
    ISR = 'ISR'
    MERAKI_MX = 'Meraki MX'
    VIPTELA_CEDGE = 'Viptela cEdge'
    VIPTELA_VEDGE = 'Viptela vEdge'
    OTHER = 'other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeviceType from a JSON string"""
        return cls(json.loads(json_str))


