# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DiscoveryResponse(BaseModel):
    """
    The properties of the Taxii discovery root for the threat intelligence feed.
    """ # noqa: E501
    api_roots: List[StrictStr] = Field(description="The list of URLs for the available API roots.")
    contact: Optional[StrictStr] = Field(default=None, description="The email address that the system can use to contact the owner of the Taxii discovery server.")
    default: Optional[StrictStr] = Field(default=None, description="The URL of the default API root.")
    description: Optional[StrictStr] = Field(default=None, description="The description for the Taxii discovery server.")
    max_content_length: Optional[StrictInt] = Field(default=None, description="The maximum content length of the response in bytes.")
    title: StrictStr = Field(description="The title of the Taxii discovery server.")
    __properties: ClassVar[List[str]] = ["api_roots", "contact", "default", "description", "max_content_length", "title"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiscoveryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if contact (nullable) is None
        # and model_fields_set contains the field
        if self.contact is None and "contact" in self.model_fields_set:
            _dict['contact'] = None

        # set to None if default (nullable) is None
        # and model_fields_set contains the field
        if self.default is None and "default" in self.model_fields_set:
            _dict['default'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if max_content_length (nullable) is None
        # and model_fields_set contains the field
        if self.max_content_length is None and "max_content_length" in self.model_fields_set:
            _dict['max_content_length'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiscoveryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_roots": obj.get("api_roots"),
            "contact": obj.get("contact"),
            "default": obj.get("default"),
            "description": obj.get("description"),
            "max_content_length": obj.get("max_content_length"),
            "title": obj.get("title")
        })
        return _obj


