# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from secure_access.models.dlp_rule_event_by_type import DLPRuleEventByType
from secure_access.models.saas_api_dlp_rule_event import SaasApiDlpRuleEvent
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

DLPRULEEVENT_ONE_OF_SCHEMAS = ["DLPRuleEventByType", "SaasApiDlpRuleEvent"]

class DlpRuleEvent(BaseModel):
    """
    The specific type of DLP rule event returned by the system in the response.
    """
    # data type: DLPRuleEventByType
    oneof_schema_1_validator: Optional[DLPRuleEventByType] = None
    # data type: SaasApiDlpRuleEvent
    oneof_schema_2_validator: Optional[SaasApiDlpRuleEvent] = None
    actual_instance: Optional[Union[DLPRuleEventByType, SaasApiDlpRuleEvent]] = None
    one_of_schemas: Set[str] = { "DLPRuleEventByType", "SaasApiDlpRuleEvent" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = DlpRuleEvent.model_construct()
        error_messages = []
        match = 0
        # validate data type: DLPRuleEventByType
        if not isinstance(v, DLPRuleEventByType):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DLPRuleEventByType`")
        else:
            match += 1
        # validate data type: SaasApiDlpRuleEvent
        if not isinstance(v, SaasApiDlpRuleEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SaasApiDlpRuleEvent`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in DlpRuleEvent with oneOf schemas: DLPRuleEventByType, SaasApiDlpRuleEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in DlpRuleEvent with oneOf schemas: DLPRuleEventByType, SaasApiDlpRuleEvent. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into DLPRuleEventByType
        try:
            instance.actual_instance = DLPRuleEventByType.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SaasApiDlpRuleEvent
        try:
            instance.actual_instance = SaasApiDlpRuleEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into DlpRuleEvent with oneOf schemas: DLPRuleEventByType, SaasApiDlpRuleEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into DlpRuleEvent with oneOf schemas: DLPRuleEventByType, SaasApiDlpRuleEvent. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], DLPRuleEventByType, SaasApiDlpRuleEvent]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


