# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from secure_access.models.data_loss_prevention_action import DataLossPreventionAction
from secure_access.models.data_loss_prevention_application import DataLossPreventionApplication
from secure_access.models.data_loss_prevention_identity import DataLossPreventionIdentity
from secure_access.models.data_loss_prevention_severity import DataLossPreventionSeverity
from secure_access.models.id_name_ref import IdNameRef
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DLPRule(BaseModel):
    """
    The properties of a DLP rule.
    """ # noqa: E501
    action: Optional[DataLossPreventionAction] = DataLossPreventionAction.MONITOR
    applications: Optional[List[DataLossPreventionApplication]] = Field(default=None, description="List of applications associated with the rule. This field is only included if `includeDetails` contains `applications`. ")
    classifications: Optional[List[IdNameRef]] = Field(default=None, description="The list of data classifications associated with the rule.  This field is only included if `includeDetails` contains `classifications`.")
    description: Optional[StrictStr] = Field(default=None, description="The description of the DLP rule.")
    enabled: Optional[StrictBool] = Field(default=None, description="Specifies whether the system enabled the DLP rule.")
    id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the DLP rule.")
    identities: Optional[List[DataLossPreventionIdentity]] = Field(default=None, description="List of identities associated with the rule. This field is only included if `includeDetails` contains `identities`. ")
    name: Optional[Annotated[str, Field(min_length=6, strict=True, max_length=255)]] = Field(default=None, description="The name of the DLP rule.")
    secure_icap_enabled: Optional[StrictBool] = Field(default=None, description="Indicates whether Secure ICAP is enabled.", alias="secureIcapEnabled")
    severity: Optional[DataLossPreventionSeverity] = None
    __properties: ClassVar[List[str]] = ["action", "applications", "classifications", "description", "enabled", "id", "identities", "name", "secureIcapEnabled", "severity"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DLPRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in applications (list)
        _items = []
        if self.applications:
            for _item_applications in self.applications:
                if _item_applications:
                    _items.append(_item_applications.to_dict())
            _dict['applications'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in classifications (list)
        _items = []
        if self.classifications:
            for _item_classifications in self.classifications:
                if _item_classifications:
                    _items.append(_item_classifications.to_dict())
            _dict['classifications'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in identities (list)
        _items = []
        if self.identities:
            for _item_identities in self.identities:
                if _item_identities:
                    _items.append(_item_identities.to_dict())
            _dict['identities'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DLPRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action") if obj.get("action") is not None else DataLossPreventionAction.MONITOR,
            "applications": [DataLossPreventionApplication.from_dict(_item) for _item in obj["applications"]] if obj.get("applications") is not None else None,
            "classifications": [IdNameRef.from_dict(_item) for _item in obj["classifications"]] if obj.get("classifications") is not None else None,
            "description": obj.get("description"),
            "enabled": obj.get("enabled"),
            "id": obj.get("id"),
            "identities": [DataLossPreventionIdentity.from_dict(_item) for _item in obj["identities"]] if obj.get("identities") is not None else None,
            "name": obj.get("name"),
            "secureIcapEnabled": obj.get("secureIcapEnabled"),
            "severity": obj.get("severity")
        })
        return _obj


