# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from secure_access.models.do_not_decrypt_list_data_decrypt_exception_categories_inner import DoNotDecryptListDataDecryptExceptionCategoriesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DoNotDecryptListData(BaseModel):
    """
    The properties of the Do Not Decrypt list.
    """ # noqa: E501
    bundle_type_id: Optional[StrictInt] = Field(default=None, description="The bundle type associated with the destination list.", alias="bundleTypeId")
    created_at: Optional[datetime] = Field(default=None, description="The date and time (ISO 8601-formatted timestamp) when the system created the Do Not Decrypt list.", alias="createdAt")
    decrypt_exception_categories: Optional[List[DoNotDecryptListDataDecryptExceptionCategoriesInner]] = Field(default=None, description="The list of decrypt exception categories included in the Do Not Decrypt list.", alias="decryptExceptionCategories")
    exceptionapplicationlist_id: Optional[StrictInt] = Field(default=None, description="The unique idenitifer of the application list associated with the Access policy.", alias="exceptionapplicationlistId")
    exceptiondomainlist_id: Optional[StrictInt] = Field(default=None, description="The unique identifier of the destination list associated with the Access policy.", alias="exceptiondomainlistId")
    id: Optional[StrictInt] = Field(default=None, description="The unique identifier of the Do Not Decrypt list.")
    is_default: Optional[StrictBool] = Field(default=None, description="Indicates whether the list is the default Do Not Decryption list for the organization.", alias="isDefault")
    modified_at: Optional[datetime] = Field(default=None, description="The date and time (ISO 8601-formatted timestamp) when the system updated the Do Not Decrypt list.", alias="modifiedAt")
    name: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="The name of the Do Not Decrypt list.")
    organization_id: Optional[StrictInt] = Field(default=None, description="The unique identifier of the organization.", alias="organizationId")
    total_applications: Optional[StrictInt] = Field(default=None, description="The total number of applications in the application list associated with the Do Not Decrypt list.", alias="totalApplications")
    total_domains: Optional[StrictInt] = Field(default=None, description="The total number of domains in the destination list associated with the Do Not Decrypt list.", alias="totalDomains")
    total_ips: Optional[StrictInt] = Field(default=None, description="The total number of IP addresses in the destination list associated with the Do Not Decrypt list.", alias="totalIps")
    __properties: ClassVar[List[str]] = ["bundleTypeId", "createdAt", "decryptExceptionCategories", "exceptionapplicationlistId", "exceptiondomainlistId", "id", "isDefault", "modifiedAt", "name", "organizationId", "totalApplications", "totalDomains", "totalIps"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DoNotDecryptListData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created_at",
            "modified_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in decrypt_exception_categories (list)
        _items = []
        if self.decrypt_exception_categories:
            for _item_decrypt_exception_categories in self.decrypt_exception_categories:
                if _item_decrypt_exception_categories:
                    _items.append(_item_decrypt_exception_categories.to_dict())
            _dict['decryptExceptionCategories'] = _items
        # set to None if exceptionapplicationlist_id (nullable) is None
        # and model_fields_set contains the field
        if self.exceptionapplicationlist_id is None and "exceptionapplicationlist_id" in self.model_fields_set:
            _dict['exceptionapplicationlistId'] = None

        # set to None if exceptiondomainlist_id (nullable) is None
        # and model_fields_set contains the field
        if self.exceptiondomainlist_id is None and "exceptiondomainlist_id" in self.model_fields_set:
            _dict['exceptiondomainlistId'] = None

        # set to None if is_default (nullable) is None
        # and model_fields_set contains the field
        if self.is_default is None and "is_default" in self.model_fields_set:
            _dict['isDefault'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DoNotDecryptListData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bundleTypeId": obj.get("bundleTypeId"),
            "createdAt": obj.get("createdAt"),
            "decryptExceptionCategories": [DoNotDecryptListDataDecryptExceptionCategoriesInner.from_dict(_item) for _item in obj["decryptExceptionCategories"]] if obj.get("decryptExceptionCategories") is not None else None,
            "exceptionapplicationlistId": obj.get("exceptionapplicationlistId"),
            "exceptiondomainlistId": obj.get("exceptiondomainlistId"),
            "id": obj.get("id"),
            "isDefault": obj.get("isDefault"),
            "modifiedAt": obj.get("modifiedAt"),
            "name": obj.get("name"),
            "organizationId": obj.get("organizationId"),
            "totalApplications": obj.get("totalApplications"),
            "totalDomains": obj.get("totalDomains"),
            "totalIps": obj.get("totalIps")
        })
        return _obj


