# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from uuid import UUID
from secure_access.models.columns_edm_with_id_inner import ColumnsEdmWithIdInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EDMIdentifierResponse(BaseModel):
    """
    The properties of the Exact Data Match (EDM) data identifier.
    """ # noqa: E501
    columns: List[ColumnsEdmWithIdInner] = Field(description="The list of columns for the Exact Data Match (EDM) identifier.")
    creation_time: StrictInt = Field(description="The date and time represented in seconds since the UNIX Epoch when the system created the EDM data identifier.", alias="creationTime")
    description: Annotated[str, Field(strict=True, max_length=255)] = Field(description="The description of the EDM data identifier.")
    id: UUID = Field(description="The unique identifier of the EDM data identifier.")
    is_active: StrictBool = Field(description="Specifies whether the EDM data identifier is active.", alias="isActive")
    minimum_number_of_matches: StrictInt = Field(description="The minimum number of matches required for Exact Data Match (EDM).", alias="minimumNumberOfMatches")
    modification_time: StrictInt = Field(description="The date and time represented in seconds since the UNIX Epoch when the system updated the EDM data identifier.", alias="modificationTime")
    name: Annotated[str, Field(strict=True, max_length=255)] = Field(description="The name of the EDM data identifier.")
    __properties: ClassVar[List[str]] = ["columns", "creationTime", "description", "id", "isActive", "minimumNumberOfMatches", "modificationTime", "name"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EDMIdentifierResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in columns (list)
        _items = []
        if self.columns:
            for _item_columns in self.columns:
                if _item_columns:
                    _items.append(_item_columns.to_dict())
            _dict['columns'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EDMIdentifierResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "columns": [ColumnsEdmWithIdInner.from_dict(_item) for _item in obj["columns"]] if obj.get("columns") is not None else None,
            "creationTime": obj.get("creationTime"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "isActive": obj.get("isActive"),
            "minimumNumberOfMatches": obj.get("minimumNumberOfMatches"),
            "modificationTime": obj.get("modificationTime"),
            "name": obj.get("name")
        })
        return _obj


