# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from secure_access.models.severity_alert import SeverityAlert
from secure_access.models.status_alert import StatusAlert
from secure_access.models.time_range import TimeRange
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FiltersAlertObject(BaseModel):
    """
    The properties of the filters query parameter. Filter for the attributes of the alerts.
    """ # noqa: E501
    alert_name: Optional[StrictStr] = Field(default=None, description="The name of the alert.")
    created_after: Optional[datetime] = Field(default=None, description="Filter for the alerts in the collection that the system created after the timestamp. Provide a date and time (ISO 8601) using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `created_after` query parameter with the `time_range` filter.")
    include_context: Optional[StrictBool] = Field(default=False, description="Include the context field in each alert response. The context contains additional metadata about the alert.")
    modified_at: Optional[datetime] = Field(default=None, description="The time and date (ISO 8601 timestamp) when the system last modified the alert.")
    only_active_alerts_count: Optional[StrictBool] = Field(default=False, description="Specify whether to query for the count of the active alerts only.")
    pattern_search: Optional[StrictStr] = Field(default=None, description="Provide a search pattern to query for by the alert name, alert rule name, or alert rule category name.")
    severity: Optional[SeverityAlert] = None
    status: Optional[StatusAlert] = None
    time_range: Optional[TimeRange] = None
    __properties: ClassVar[List[str]] = ["alert_name", "created_after", "include_context", "modified_at", "only_active_alerts_count", "pattern_search", "severity", "status", "time_range"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FiltersAlertObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of time_range
        if self.time_range:
            _dict['time_range'] = self.time_range.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FiltersAlertObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alert_name": obj.get("alert_name"),
            "created_after": obj.get("created_after"),
            "include_context": obj.get("include_context") if obj.get("include_context") is not None else False,
            "modified_at": obj.get("modified_at"),
            "only_active_alerts_count": obj.get("only_active_alerts_count") if obj.get("only_active_alerts_count") is not None else False,
            "pattern_search": obj.get("pattern_search"),
            "severity": obj.get("severity"),
            "status": obj.get("status"),
            "time_range": TimeRange.from_dict(obj["time_range"]) if obj.get("time_range") is not None else None
        })
        return _obj


