# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Format(str, Enum):
    """
    The label that describes the format of the outbound security event.
    """

    """
    allowed enum values
    """
    SECUREACCESS_DOT_EVENTS_DOT_SECURITY_DOT_SPLUNK_MINUS_HEC_DOT_V1 = 'secureaccess.events.security.splunk-hec.v1'
    SECUREACCESS_DOT_EVENTS_DOT_SECURITY_DOT_CLOUDEVENTS_DOT_V1 = 'secureaccess.events.security.cloudevents.v1'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Format from a JSON string"""
        return cls(json.loads(json_str))


