# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from secure_access.models.level import Level
from secure_access.models.service_name import ServiceName
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NetworkTunnelEvent(BaseModel):
    """
    The properties of the event for the network tunnel.
    """ # noqa: E501
    bgp_peer_ip: Optional[StrictStr] = Field(default=None, description="The CIDR netmask used to limit the customer peers that can talk to the headend BGP.", alias="bgpPeerIp")
    datacenter: Optional[StrictStr] = Field(default=None, description="The canonical name of the data center where the system deployed the hub.")
    datacenter_ip: Optional[StrictStr] = Field(default=None, description="The comma-separated list of IP addresses of the data centers where the system deployed the hub.", alias="datacenterIp")
    device_type: Optional[StrictStr] = Field(default=None, description="The type of the device.", alias="deviceType")
    hub_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the hub.", alias="hubId")
    hub_is_primary: Optional[StrictBool] = Field(default=None, description="Specifies whether the hub is a primary data center.", alias="hubIsPrimary")
    ike_auth_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the IKE session for the network tunnel.", alias="ikeAuthId")
    ike_customer_address: Optional[StrictStr] = Field(default=None, description="The IP address used by the end user for the IKE session.", alias="ikeCustomerAddress")
    ike_customer_port: Optional[StrictInt] = Field(default=None, description="The port used by the end user for the IKE session.", alias="ikeCustomerPort")
    ike_spi: Optional[StrictStr] = Field(default=None, alias="ikeSpi")
    level: Optional[Level] = None
    message: Optional[StrictStr] = Field(default=None, description="The message for the event.")
    network_tunnel_group_id: Optional[StrictInt] = Field(default=None, description="The unique identifier of the network tunnel group.", alias="networkTunnelGroupId")
    network_tunnel_group_label: Optional[StrictStr] = Field(default=None, description="The name of the network tunnel group. A Network Tunnel Group name is a sequence of 1–50 characters, which does not contain any special characters other than spaces and hyphens.", alias="networkTunnelGroupLabel")
    origin_id: Optional[StrictInt] = Field(default=None, description="The unique identifier of the network device that established the IPsec tunnel.", alias="originId")
    origin_type: Optional[StrictInt] = Field(default=None, description="The numeric type that identifies the origin.", alias="originType")
    region: Optional[StrictStr] = Field(default=None, description="The name of the region that the system uses to obtain the primary and secondary data centers for the Hubs.")
    service_name: Optional[ServiceName] = Field(default=None, alias="serviceName")
    timestamp: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The timestamp represented in seconds.")
    tunnel_id: Optional[StrictInt] = Field(default=None, description="The unique identifier of the network tunnel.", alias="tunnelId")
    umbrella_org_id: Optional[StrictInt] = Field(default=None, description="The unique identifier of the organization.", alias="umbrellaOrgId")
    __properties: ClassVar[List[str]] = ["bgpPeerIp", "datacenter", "datacenterIp", "deviceType", "hubId", "hubIsPrimary", "ikeAuthId", "ikeCustomerAddress", "ikeCustomerPort", "ikeSpi", "level", "message", "networkTunnelGroupId", "networkTunnelGroupLabel", "originId", "originType", "region", "serviceName", "timestamp", "tunnelId", "umbrellaOrgId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NetworkTunnelEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "datacenter",
            "datacenter_ip",
            "hub_id",
            "hub_is_primary",
            "network_tunnel_group_id",
            "umbrella_org_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NetworkTunnelEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bgpPeerIp": obj.get("bgpPeerIp"),
            "datacenter": obj.get("datacenter"),
            "datacenterIp": obj.get("datacenterIp"),
            "deviceType": obj.get("deviceType"),
            "hubId": obj.get("hubId"),
            "hubIsPrimary": obj.get("hubIsPrimary"),
            "ikeAuthId": obj.get("ikeAuthId"),
            "ikeCustomerAddress": obj.get("ikeCustomerAddress"),
            "ikeCustomerPort": obj.get("ikeCustomerPort"),
            "ikeSpi": obj.get("ikeSpi"),
            "level": obj.get("level"),
            "message": obj.get("message"),
            "networkTunnelGroupId": obj.get("networkTunnelGroupId"),
            "networkTunnelGroupLabel": obj.get("networkTunnelGroupLabel"),
            "originId": obj.get("originId"),
            "originType": obj.get("originType"),
            "region": obj.get("region"),
            "serviceName": obj.get("serviceName"),
            "timestamp": obj.get("timestamp"),
            "tunnelId": obj.get("tunnelId"),
            "umbrellaOrgId": obj.get("umbrellaOrgId")
        })
        return _obj


