# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NotificationTypeAll(str, Enum):
    """
    The type of the notification for the alert rule.
    """

    """
    allowed enum values
    """
    EMAIL = 'email'
    WEBHOOK = 'webhook'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NotificationTypeAll from a JSON string"""
        return cls(json.loads(json_str))


