# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from secure_access.models.intune_config_input import IntuneConfigInput
from secure_access.models.jamf_config_input import JamfConfigInput
from secure_access.models.patch_integration_config_input import PatchIntegrationConfigInput
from secure_access.models.security_events_config_patch_input import SecurityEventsConfigPatchInput
from secure_access.models.webhook_config_input import WebhookConfigInput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PatchIntegrationBody(BaseModel):
    """
    PatchIntegrationBody
    """ # noqa: E501
    config: Optional[PatchIntegrationConfigInput] = None
    intune_config: Optional[IntuneConfigInput] = Field(default=None, alias="intuneConfig")
    jamf_config: Optional[JamfConfigInput] = Field(default=None, alias="jamfConfig")
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=250)]] = Field(default=None, description="The name of the integration.")
    security_events_config: Optional[SecurityEventsConfigPatchInput] = Field(default=None, alias="securityEventsConfig")
    webhook_config: Optional[WebhookConfigInput] = Field(default=None, alias="webhookConfig")
    __properties: ClassVar[List[str]] = ["config", "intuneConfig", "jamfConfig", "name", "securityEventsConfig", "webhookConfig"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchIntegrationBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of intune_config
        if self.intune_config:
            _dict['intuneConfig'] = self.intune_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of jamf_config
        if self.jamf_config:
            _dict['jamfConfig'] = self.jamf_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of security_events_config
        if self.security_events_config:
            _dict['securityEventsConfig'] = self.security_events_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of webhook_config
        if self.webhook_config:
            _dict['webhookConfig'] = self.webhook_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchIntegrationBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "config": PatchIntegrationConfigInput.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "intuneConfig": IntuneConfigInput.from_dict(obj["intuneConfig"]) if obj.get("intuneConfig") is not None else None,
            "jamfConfig": JamfConfigInput.from_dict(obj["jamfConfig"]) if obj.get("jamfConfig") is not None else None,
            "name": obj.get("name"),
            "securityEventsConfig": SecurityEventsConfigPatchInput.from_dict(obj["securityEventsConfig"]) if obj.get("securityEventsConfig") is not None else None,
            "webhookConfig": WebhookConfigInput.from_dict(obj["webhookConfig"]) if obj.get("webhookConfig") is not None else None
        })
        return _obj


