# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from secure_access.models.application import Application
from secure_access.models.data_loss_prevention_application_category import DataLossPreventionApplicationCategory
from secure_access.models.identity import Identity
from secure_access.models.private_resource import PrivateResource
from secure_access.models.private_resource_group import PrivateResourceGroup
from secure_access.models.rule import Rule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RealTimeDlpRuleEvent(BaseModel):
    """
    The properties of the Real-Time DLP rule event.
    """ # noqa: E501
    action: Optional[StrictStr] = Field(default=None, description="The action triggered by the DLP rule.")
    application: Optional[Application] = None
    application_category: Optional[DataLossPreventionApplicationCategory] = Field(default=None, alias="applicationCategory")
    content_type: Optional[StrictStr] = Field(default=None, description="The type of data that triggered the DLP rule event.", alias="contentType")
    destination_url: Optional[StrictStr] = Field(default=None, description="The URL where the end user uploadedor posted the file.", alias="destinationUrl")
    detected: Optional[datetime] = Field(default=None, description="The date and time when the system detected the content, formatted as an ISO 8601 timestamp.")
    direction: Optional[StrictStr] = Field(default=None, description="The direction of the detected traffic.")
    event_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the event.", alias="eventId")
    file_labels: Optional[List[StrictStr]] = Field(default=None, description="The list of labels associated with the file.", alias="fileLabels")
    file_name: Optional[StrictStr] = Field(default=None, description="The name of the file where the system identified a classification match. For messages or posts, the system returns `Content`.", alias="fileName")
    identity: Optional[Identity] = None
    private_resource: Optional[PrivateResource] = Field(default=None, alias="privateResource")
    private_resource_group: Optional[PrivateResourceGroup] = Field(default=None, alias="privateResourceGroup")
    rule: Optional[Rule] = None
    severity: Optional[StrictStr] = Field(default=None, description="The severity of the DLP rule.")
    sha256_hash: Optional[StrictStr] = Field(default=None, description="The unique SHA256 hash of the file.", alias="sha256Hash")
    total_size_in_bytes: Optional[StrictInt] = Field(default=None, description="The size of the file in bytes that triggered the DLP rule event.", alias="totalSizeInBytes")
    __properties: ClassVar[List[str]] = ["action", "application", "applicationCategory", "contentType", "destinationUrl", "detected", "direction", "eventId", "fileLabels", "fileName", "identity", "privateResource", "privateResourceGroup", "rule", "severity", "sha256Hash", "totalSizeInBytes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RealTimeDlpRuleEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of application
        if self.application:
            _dict['application'] = self.application.to_dict()
        # override the default output from pydantic by calling `to_dict()` of application_category
        if self.application_category:
            _dict['applicationCategory'] = self.application_category.to_dict()
        # override the default output from pydantic by calling `to_dict()` of identity
        if self.identity:
            _dict['identity'] = self.identity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of private_resource
        if self.private_resource:
            _dict['privateResource'] = self.private_resource.to_dict()
        # override the default output from pydantic by calling `to_dict()` of private_resource_group
        if self.private_resource_group:
            _dict['privateResourceGroup'] = self.private_resource_group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rule
        if self.rule:
            _dict['rule'] = self.rule.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RealTimeDlpRuleEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "application": Application.from_dict(obj["application"]) if obj.get("application") is not None else None,
            "applicationCategory": DataLossPreventionApplicationCategory.from_dict(obj["applicationCategory"]) if obj.get("applicationCategory") is not None else None,
            "contentType": obj.get("contentType"),
            "destinationUrl": obj.get("destinationUrl"),
            "detected": obj.get("detected"),
            "direction": obj.get("direction"),
            "eventId": obj.get("eventId"),
            "fileLabels": obj.get("fileLabels"),
            "fileName": obj.get("fileName"),
            "identity": Identity.from_dict(obj["identity"]) if obj.get("identity") is not None else None,
            "privateResource": PrivateResource.from_dict(obj["privateResource"]) if obj.get("privateResource") is not None else None,
            "privateResourceGroup": PrivateResourceGroup.from_dict(obj["privateResourceGroup"]) if obj.get("privateResourceGroup") is not None else None,
            "rule": Rule.from_dict(obj["rule"]) if obj.get("rule") is not None else None,
            "severity": obj.get("severity"),
            "sha256Hash": obj.get("sha256Hash"),
            "totalSizeInBytes": obj.get("totalSizeInBytes")
        })
        return _obj


