# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from secure_access.models.application_saas_api import ApplicationSaasAPI
from secure_access.models.rule import Rule
from secure_access.models.saas_api_event_user import SaasApiEventUser
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SaasApiDlpRuleEvent(BaseModel):
    """
    The properties of the SaaS API DLP rule event.
    """ # noqa: E501
    action: Optional[StrictStr] = Field(default=None, description="The action triggered by the DLP rule.")
    actor: Optional[SaasApiEventUser] = None
    application: Optional[ApplicationSaasAPI] = None
    content_type: Optional[StrictStr] = Field(default=None, description="The type of data that triggered the DLP rule event.", alias="contentType")
    destination_url: Optional[StrictStr] = Field(default=None, description="The URL where the end user uploadedor posted the file.", alias="destinationUrl")
    detected: Optional[datetime] = Field(default=None, description="The date and time when the system detected the content, formatted as an ISO 8601 timestamp.")
    event_id: Optional[StrictStr] = Field(default=None, description="A unique identifier for the DLP rule event.", alias="eventId")
    exposure: Optional[StrictStr] = Field(default=None, description="An indication of who can see the file (internal or external users).")
    file_name: Optional[StrictStr] = Field(default=None, description="The name of the file where the system identified a classification match. For messages or posts, the system returns `Content`.", alias="fileName")
    instance_name: Optional[StrictStr] = Field(default=None, description="The name of the authorized tenant for a SaaS API platform.", alias="instanceName")
    owner: Optional[SaasApiEventUser] = None
    resource_id: Optional[StrictStr] = Field(default=None, description="The URL for the resource associated with the content that triggered the violation.", alias="resourceId")
    resource_name: Optional[StrictStr] = Field(default=None, description="The name of the resource associated with the content that triggered the violation.", alias="resourceName")
    rule: Optional[Rule] = None
    severity: Optional[StrictStr] = Field(default=None, description="The severity of the DLP rule.")
    sha256_hash: Optional[StrictStr] = Field(default=None, description="The unique SHA256 hash of the file.", alias="sha256Hash")
    total_size_in_bytes: Optional[StrictInt] = Field(default=None, description="The size of the file in bytes that triggered the DLP rule event.", alias="totalSizeInBytes")
    __properties: ClassVar[List[str]] = ["action", "actor", "application", "contentType", "destinationUrl", "detected", "eventId", "exposure", "fileName", "instanceName", "owner", "resourceId", "resourceName", "rule", "severity", "sha256Hash", "totalSizeInBytes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SaasApiDlpRuleEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of actor
        if self.actor:
            _dict['actor'] = self.actor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of application
        if self.application:
            _dict['application'] = self.application.to_dict()
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rule
        if self.rule:
            _dict['rule'] = self.rule.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SaasApiDlpRuleEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "actor": SaasApiEventUser.from_dict(obj["actor"]) if obj.get("actor") is not None else None,
            "application": ApplicationSaasAPI.from_dict(obj["application"]) if obj.get("application") is not None else None,
            "contentType": obj.get("contentType"),
            "destinationUrl": obj.get("destinationUrl"),
            "detected": obj.get("detected"),
            "eventId": obj.get("eventId"),
            "exposure": obj.get("exposure"),
            "fileName": obj.get("fileName"),
            "instanceName": obj.get("instanceName"),
            "owner": SaasApiEventUser.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "resourceId": obj.get("resourceId"),
            "resourceName": obj.get("resourceName"),
            "rule": Rule.from_dict(obj["rule"]) if obj.get("rule") is not None else None,
            "severity": obj.get("severity"),
            "sha256Hash": obj.get("sha256Hash"),
            "totalSizeInBytes": obj.get("totalSizeInBytes")
        })
        return _obj


