# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from secure_access.models.bundle_type_id import BundleTypeId
from secure_access.models.reporting import Reporting
from secure_access.models.tenant_controls_restriction import TenantControlsRestriction
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SecurityProfileResponse(BaseModel):
    """
    The properties of the Security profile.
    """ # noqa: E501
    application_aup_setting_group_id: Optional[StrictInt] = Field(description="The group ID of the Application setting.", alias="applicationAupSettingGroupId")
    aup_setting_group_id: Optional[StrictInt] = Field(description="The group ID of the Category setting.", alias="aupSettingGroupId")
    bundle_type_id: BundleTypeId = Field(alias="bundleTypeId")
    category_setting: Optional[Dict[str, Any]] = Field(default=None, description="The properties of the Content Category setting.", alias="categorySetting")
    created_at: StrictInt = Field(description="The date and time (in seconds since the Unix Epoch) when the system created the Security profile setting.", alias="createdAt")
    domainlists: Optional[List[Any]] = Field(default=None, description="The list of destination lists in the organization.")
    file_inspection_setting: Optional[Dict[str, Any]] = Field(default=None, description="The properties of the File Inspection setting.", alias="fileInspectionSetting")
    file_inspection_setting_group_id: Optional[StrictInt] = Field(default=None, description="The group ID of the File Inspection setting.", alias="fileInspectionSettingGroupId")
    frontend_modified_at: Optional[StrictInt] = Field(default=None, description="The date and time (in seconds since the Unix Epoch) when the system modified the dashboard.", alias="frontendModifiedAt")
    id: StrictInt = Field(description="The ID of the Security profile.")
    identity_count: Optional[StrictInt] = Field(default=None, description="The number of resources in the organization.", alias="identityCount")
    is_default: StrictBool = Field(description="Specifies whether the setting is the default setting.", alias="isDefault")
    is_fwaas_default: Optional[StrictBool] = Field(description="Specifies whether the Security profile for the cloud-delivered firewall is the default Security profile.", alias="isFwaasDefault")
    is_swg_default: Optional[StrictBool] = Field(description="Specifies whether the Security profile for the secure web gateway (SWG) is the default Security profile.", alias="isSwgDefault")
    lander_setting_group_id: Optional[StrictInt] = Field(default=None, description="The group ID of the Notification setting.", alias="landerSettingGroupId")
    modified_at: StrictInt = Field(description="The date and time (in seconds since the Unix Epoch) when the system created the Security profile setting.", alias="modifiedAt")
    name: StrictStr = Field(description="The name of the Security profile.")
    organization_id: StrictInt = Field(description="The ID of the organization.", alias="organizationId")
    policy_setting: Optional[Dict[str, Any]] = Field(default=None, description="The properties of the Policy setting.", alias="policySetting")
    policy_setting_group_id: Optional[StrictInt] = Field(default=None, description="The group ID of the Policy setting.", alias="policySettingGroupId")
    priority: Optional[StrictInt] = Field(default=None, description="The priority of the Security profile.")
    reporting: Optional[Reporting] = None
    restriction: Optional[TenantControlsRestriction] = None
    security_setting: Optional[Dict[str, Any]] = Field(default=None, description="The properties of the Security settings.", alias="securitySetting")
    security_setting_group_id: Optional[StrictInt] = Field(default=None, description="The group ID of the Security setting.", alias="securitySettingGroupId")
    setting_group_bypass_inspection_group_id: Optional[StrictInt] = Field(default=None, description="The group ID of the Bypass Inspection setting.", alias="settingGroupBypassInspectionGroupId")
    __properties: ClassVar[List[str]] = ["applicationAupSettingGroupId", "aupSettingGroupId", "bundleTypeId", "categorySetting", "createdAt", "domainlists", "fileInspectionSetting", "fileInspectionSettingGroupId", "frontendModifiedAt", "id", "identityCount", "isDefault", "isFwaasDefault", "isSwgDefault", "landerSettingGroupId", "modifiedAt", "name", "organizationId", "policySetting", "policySettingGroupId", "priority", "reporting", "restriction", "securitySetting", "securitySettingGroupId", "settingGroupBypassInspectionGroupId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SecurityProfileResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of restriction
        if self.restriction:
            _dict['restriction'] = self.restriction.to_dict()
        # set to None if application_aup_setting_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.application_aup_setting_group_id is None and "application_aup_setting_group_id" in self.model_fields_set:
            _dict['applicationAupSettingGroupId'] = None

        # set to None if aup_setting_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.aup_setting_group_id is None and "aup_setting_group_id" in self.model_fields_set:
            _dict['aupSettingGroupId'] = None

        # set to None if is_fwaas_default (nullable) is None
        # and model_fields_set contains the field
        if self.is_fwaas_default is None and "is_fwaas_default" in self.model_fields_set:
            _dict['isFwaasDefault'] = None

        # set to None if is_swg_default (nullable) is None
        # and model_fields_set contains the field
        if self.is_swg_default is None and "is_swg_default" in self.model_fields_set:
            _dict['isSwgDefault'] = None

        # set to None if setting_group_bypass_inspection_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.setting_group_bypass_inspection_group_id is None and "setting_group_bypass_inspection_group_id" in self.model_fields_set:
            _dict['settingGroupBypassInspectionGroupId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SecurityProfileResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "applicationAupSettingGroupId": obj.get("applicationAupSettingGroupId"),
            "aupSettingGroupId": obj.get("aupSettingGroupId"),
            "bundleTypeId": obj.get("bundleTypeId"),
            "categorySetting": obj.get("categorySetting"),
            "createdAt": obj.get("createdAt"),
            "domainlists": obj.get("domainlists"),
            "fileInspectionSetting": obj.get("fileInspectionSetting"),
            "fileInspectionSettingGroupId": obj.get("fileInspectionSettingGroupId"),
            "frontendModifiedAt": obj.get("frontendModifiedAt"),
            "id": obj.get("id"),
            "identityCount": obj.get("identityCount"),
            "isDefault": obj.get("isDefault"),
            "isFwaasDefault": obj.get("isFwaasDefault"),
            "isSwgDefault": obj.get("isSwgDefault"),
            "landerSettingGroupId": obj.get("landerSettingGroupId"),
            "modifiedAt": obj.get("modifiedAt"),
            "name": obj.get("name"),
            "organizationId": obj.get("organizationId"),
            "policySetting": obj.get("policySetting"),
            "policySettingGroupId": obj.get("policySettingGroupId"),
            "priority": obj.get("priority"),
            "reporting": obj.get("reporting"),
            "restriction": TenantControlsRestriction.from_dict(obj["restriction"]) if obj.get("restriction") is not None else None,
            "securitySetting": obj.get("securitySetting"),
            "securitySettingGroupId": obj.get("securitySettingGroupId"),
            "settingGroupBypassInspectionGroupId": obj.get("settingGroupBypassInspectionGroupId")
        })
        return _obj


