# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from secure_access.models.reporting import Reporting
from secure_access.models.saml import Saml
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SecurityProfileUpdateRequest(BaseModel):
    """
    The properties used to update a security profile.
    """ # noqa: E501
    ai_supply_chain_categories: Optional[StrictStr] = Field(default=None, description="The encoded AI supply chain category bitmask value applied at the root request level. Sample values include 0 and encoded values such as C00000000000000000000000000000000000000000000000000000.", alias="aiSupplyChainCategories")
    application_aup_setting_group_id: Optional[StrictInt] = Field(default=None, description="The group ID of the Application setting.", alias="applicationAupSettingGroupId")
    aup_setting_group_id: Optional[StrictInt] = Field(description="The group ID of the Category setting.", alias="aupSettingGroupId")
    file_engines: Optional[StrictBool] = Field(default=None, description="Specifies whether file inspection engines is enabled for the profile.", alias="fileEngines")
    file_inspection_setting_group_id: Optional[StrictInt] = Field(default=None, description="The group ID of the File Inspection setting.", alias="fileInspectionSettingGroupId")
    file_type_blocked_for_download: Optional[List[Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="The list of identifiers for the file types blocked from downloads at the root request level.", alias="fileTypeBlockedForDownload")
    file_type_blocked_for_upload: Optional[List[Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="The list of identifiers for the file types blocked from uploads at the root request level.", alias="fileTypeBlockedForUpload")
    file_type_control_status: Optional[StrictBool] = Field(default=None, description="Specifies whether file type control should be enabled for the profile.", alias="fileTypeControlStatus")
    lander_setting_group_id: StrictInt = Field(description="The group ID of the Notification setting.", alias="landerSettingGroupId")
    name: StrictStr = Field(description="The name of the Security profile.")
    policy_setting_group_id: Optional[StrictInt] = Field(default=None, description="The group ID of the Policy setting.", alias="policySettingGroupId")
    priority: Optional[StrictInt] = Field(default=None, description="The priority of the Security profile.")
    reporting: Optional[Reporting] = None
    restriction_setting_id: Optional[StrictInt] = Field(default=None, description="The identifier of the restriction setting associated with the profile.", alias="restrictionSettingId")
    safe_search: Optional[StrictBool] = Field(default=None, description="Specifies whether Safe Search is enabled for the Security profile.", alias="safeSearch")
    saml: Optional[Saml] = None
    security_setting_group_id: StrictInt = Field(description="The group ID of the Security setting.", alias="securitySettingGroupId")
    setting_group_bypass_inspection_group_id: Optional[StrictInt] = Field(default=None, description="The group ID of the Bypass Inspection setting.", alias="settingGroupBypassInspectionGroupId")
    swg_display_block_page: Optional[StrictInt] = Field(default=None, description="Option to control the display of the block page by the Secure Web Gateway (SWG).", alias="swgDisplayBlockPage")
    tg_sandbox: Optional[StrictBool] = Field(default=None, description="Specifies whether Cisco Secure Malware Analytics is enabled for the profile.", alias="tgSandbox")
    __properties: ClassVar[List[str]] = ["aiSupplyChainCategories", "applicationAupSettingGroupId", "aupSettingGroupId", "fileEngines", "fileInspectionSettingGroupId", "fileTypeBlockedForDownload", "fileTypeBlockedForUpload", "fileTypeControlStatus", "landerSettingGroupId", "name", "policySettingGroupId", "priority", "reporting", "restrictionSettingId", "safeSearch", "saml", "securitySettingGroupId", "settingGroupBypassInspectionGroupId", "swgDisplayBlockPage", "tgSandbox"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SecurityProfileUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if application_aup_setting_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.application_aup_setting_group_id is None and "application_aup_setting_group_id" in self.model_fields_set:
            _dict['applicationAupSettingGroupId'] = None

        # set to None if aup_setting_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.aup_setting_group_id is None and "aup_setting_group_id" in self.model_fields_set:
            _dict['aupSettingGroupId'] = None

        # set to None if setting_group_bypass_inspection_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.setting_group_bypass_inspection_group_id is None and "setting_group_bypass_inspection_group_id" in self.model_fields_set:
            _dict['settingGroupBypassInspectionGroupId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SecurityProfileUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aiSupplyChainCategories": obj.get("aiSupplyChainCategories"),
            "applicationAupSettingGroupId": obj.get("applicationAupSettingGroupId"),
            "aupSettingGroupId": obj.get("aupSettingGroupId"),
            "fileEngines": obj.get("fileEngines"),
            "fileInspectionSettingGroupId": obj.get("fileInspectionSettingGroupId"),
            "fileTypeBlockedForDownload": obj.get("fileTypeBlockedForDownload"),
            "fileTypeBlockedForUpload": obj.get("fileTypeBlockedForUpload"),
            "fileTypeControlStatus": obj.get("fileTypeControlStatus"),
            "landerSettingGroupId": obj.get("landerSettingGroupId"),
            "name": obj.get("name"),
            "policySettingGroupId": obj.get("policySettingGroupId"),
            "priority": obj.get("priority"),
            "reporting": obj.get("reporting"),
            "restrictionSettingId": obj.get("restrictionSettingId"),
            "safeSearch": obj.get("safeSearch"),
            "saml": obj.get("saml"),
            "securitySettingGroupId": obj.get("securitySettingGroupId"),
            "settingGroupBypassInspectionGroupId": obj.get("settingGroupBypassInspectionGroupId"),
            "swgDisplayBlockPage": obj.get("swgDisplayBlockPage"),
            "tgSandbox": obj.get("tgSandbox")
        })
        return _obj


