# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from secure_access.models.auth_type import AuthType
from secure_access.models.threat_intelligence_feeds_credentials import ThreatIntelligenceFeedsCredentials
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ThreatIntelligenceFeedsFeedCreate(BaseModel):
    """
    Create a new active polling feed with the settings.
    """ # noqa: E501
    auth_type: AuthType = Field(alias="authType")
    collection_id: UUID = Field(description="The unique ID (UUID) of the TAXII collection. The collection ID must be a valid UUID v4 as specified in the  TAXII standard v2.1 Section 5.2.1.")
    collection_name: Optional[StrictStr] = Field(default=None, description="The name of the collection provided by the threat intelligence feed.")
    credentials: ThreatIntelligenceFeedsCredentials
    discovery_url: StrictStr = Field(description="The discovery URL for the TAXII service. The discovery URL must end with a trailing slash. For more information, see the TAXII 2.1 standard, section 4.1.")
    integration_name: StrictStr = Field(description="The name of the third-party integration.", alias="integrationName")
    root_url: StrictStr = Field(description="The root URL for the TAXII API. The root URL must end with a trailing slash. For more information, see the TAXII 2.1 standard, section 4.2.")
    __properties: ClassVar[List[str]] = ["authType", "collection_id", "collection_name", "credentials", "discovery_url", "integrationName", "root_url"]

    @field_validator('collection_id')
    def collection_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ThreatIntelligenceFeedsFeedCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of credentials
        if self.credentials:
            _dict['credentials'] = self.credentials.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ThreatIntelligenceFeedsFeedCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authType": obj.get("authType"),
            "collection_id": obj.get("collection_id"),
            "collection_name": obj.get("collection_name"),
            "credentials": ThreatIntelligenceFeedsCredentials.from_dict(obj["credentials"]) if obj.get("credentials") is not None else None,
            "discovery_url": obj.get("discovery_url"),
            "integrationName": obj.get("integrationName"),
            "root_url": obj.get("root_url")
        })
        return _obj


