# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from secure_access.models.vpn_user_connections_action import VpnUserConnectionsAction
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateVpnConnectionsRequest(BaseModel):
    """
    UpdateVpnConnectionsRequest
    """ # noqa: E501
    action: VpnUserConnectionsAction
    profile_name: Optional[StrictStr] = Field(default=None, description="The name of the VPN profile.", alias="profileName")
    region: Optional[StrictStr] = Field(default=None, description="The region where the action occurs on the VPN connection.")
    sessions: Optional[List[StrictStr]] = Field(default=None, description="The list of session IDs.")
    usernames: Optional[List[StrictStr]] = Field(default=None, description="The list of email addresses for the VPN users. The list can contain 1-500 email addresses.")
    __properties: ClassVar[List[str]] = ["action", "profileName", "region", "sessions", "usernames"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateVpnConnectionsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateVpnConnectionsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action") if obj.get("action") is not None else VpnUserConnectionsAction.DISCONNECT,
            "profileName": obj.get("profileName"),
            "region": obj.get("region"),
            "sessions": obj.get("sessions"),
            "usernames": obj.get("usernames")
        })
        return _obj


