# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from secure_access.models.conditions_alert_rule import ConditionsAlertRule
from secure_access.models.notification_info_alert_rule import NotificationInfoAlertRule
from secure_access.models.severity_alert import SeverityAlert
from secure_access.models.status_alert_rule import StatusAlertRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateAlertRuleRequest(BaseModel):
    """
    The properties of the alert rule used by the system to update an alert rule.
    """ # noqa: E501
    conditions: Optional[ConditionsAlertRule] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="The description of the alert rule.")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="The unique name of the alert rule.")
    notification_info: Optional[List[NotificationInfoAlertRule]] = Field(default=None, description="The list of notifications for the alert rule.")
    rule_type_id: Optional[StrictInt] = Field(default=None, description="The identifier of the rule type.  **Connectivity** * 1: Network tunnel group disconnected * 2: No traffic through network tunnel group  **API Anomalies** * 3: Too many requests to get an access token * 4: High percentage of API errors * 5: Large number of rate limit errors * 6: More than one client using an API credential * 7: Authentication failures * 8: Programmatic creation of more than one API credential  **Data Usage** * 9: Data usage approaching limit  **Access Rule Changes** * 10: Rule creation, deletion, changing or reordering  **Behavior Analytics** * 11: Impossible travel detected * 12: Bulk upload operations * 13: Bulk download operations * 14: Bulk delete operations * 15: DLP violation spike * 16: Upload from high-risk countries * 17: Upload to high-risk countries")
    severity: Optional[SeverityAlert] = None
    status: Optional[StatusAlertRule] = None
    __properties: ClassVar[List[str]] = ["conditions", "description", "name", "notification_info", "rule_type_id", "severity", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAlertRuleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of conditions
        if self.conditions:
            _dict['conditions'] = self.conditions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notification_info (list)
        _items = []
        if self.notification_info:
            for _item_notification_info in self.notification_info:
                if _item_notification_info:
                    _items.append(_item_notification_info.to_dict())
            _dict['notification_info'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAlertRuleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conditions": ConditionsAlertRule.from_dict(obj["conditions"]) if obj.get("conditions") is not None else None,
            "description": obj.get("description"),
            "name": obj.get("name"),
            "notification_info": [NotificationInfoAlertRule.from_dict(_item) for _item in obj["notification_info"]] if obj.get("notification_info") is not None else None,
            "rule_type_id": obj.get("rule_type_id"),
            "severity": obj.get("severity"),
            "status": obj.get("status")
        })
        return _obj


