# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202605140830
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VirtualApplianceObjectSettings(BaseModel):
    """
    The properties of the settings on the virtual appliance.
    """ # noqa: E501
    domains: Optional[List[StrictStr]] = Field(default=None, description="The list of domains.")
    external_ip: Optional[StrictStr] = Field(default=None, description="The external IP address.", alias="externalIP")
    host_type: Optional[StrictStr] = Field(default=None, description="The type of the host.", alias="hostType")
    internal_ips: Optional[List[StrictStr]] = Field(default=None, description="A list of internal IP addresses.", alias="internalIPs")
    is_dnscrypt_enabled: Optional[StrictBool] = Field(default=None, description="Specifies whether DNSCrypt is enabled.", alias="isDnscryptEnabled")
    last_sync_time: Optional[datetime] = Field(default=None, description="The date and time (ISO8601 timestamp) of the last sync.", alias="lastSyncTime")
    upgrade_error: Optional[StrictStr] = Field(default=None, description="Specifies the upgrade error.", alias="upgradeError")
    uptime: Optional[StrictInt] = Field(default=None, description="The uptime in seconds.")
    version: Optional[StrictStr] = Field(default=None, description="Specifies the version of the virtual appliance.")
    __properties: ClassVar[List[str]] = ["domains", "externalIP", "hostType", "internalIPs", "isDnscryptEnabled", "lastSyncTime", "upgradeError", "uptime", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VirtualApplianceObjectSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VirtualApplianceObjectSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domains": obj.get("domains"),
            "externalIP": obj.get("externalIP"),
            "hostType": obj.get("hostType"),
            "internalIPs": obj.get("internalIPs"),
            "isDnscryptEnabled": obj.get("isDnscryptEnabled"),
            "lastSyncTime": obj.get("lastSyncTime"),
            "upgradeError": obj.get("upgradeError"),
            "uptime": obj.get("uptime"),
            "version": obj.get("version")
        })
        return _obj


